import java.util.Random;
/**
 *  Computes some statistics about families in which the parents decide 
 *  to have children until they have at least one child of each gender.
 *  The program expects to get two command-line arguments: an int value
 * 	that determines how many families to simulate, and an int value
 *  that serves as the seed of the random numbers generated by the program.
 *  Example usage: % java OneOfEachStats 1000 1
 */
public class OneOfEachStats {
	public static void main (String[] args) {
	    int T = Integer.parseInt(args[0]);
		int seed = Integer.parseInt(args[1]);
		// Initailizes a random numbers generator with the given seed value
        Random generator = new Random(seed);  
   	    String EndOfsentence = ".";	
		String ans= "";
	    int ConterFor2 = 0;     
	    int ConterFor3 = 0;
	    int ConterFor4 = 0; 
        int colcoltion = 0;
	    char boy = 'b';
	    char girl = 'g';
        int r = 0;
        for (; r < T; ++r) {
        ans="";
    	boolean helper = true;
        while (helper){
				double rand = generator.nextDouble(); 
		   		ans+= (rand<0.5) ? boy : girl;  
                        colcoltion++;                               ///The loop is  Generates with Math.random   													                                                                      //that fate and the character after it are different               
                for (int i = 0; i < ans.length()-1; i++) {         // And with acolcoltion to help think the Average 
            		if(ans.length()>1){
                   		if (ans.charAt(i) != ans.charAt(i+1)){
    	                		helper=false;
                	    }                                         
            	    }
                }
        }
		    if(ans.length()==2 )         
		          ConterFor2++;         
		    if(ans.length()==3 )        ///Loops that help associate with the relevant family quantity  
		         ConterFor3++;
		    if(ans.length()>=4)
		  	     ConterFor4++;
	   }
  double Average=((double)colcoltion/(double)T);    
  int chack = Math.max(ConterFor3, ConterFor2);
  int max = Math.max(chack,ConterFor4); 
  if(max==ConterFor4 ){
         EndOfsentence = " or more.";
            max = 4;
        }else if 
        (max==ConterFor2)  
            max = 2;
        else
            max = 3;
        if(r==T){     
    			System.out.println("Average: "+Average+" children to get at least one of each gender."+"\n"+
                        "Number of families with 2 children: "+ConterFor2+"\n"+
                        "Number of families with 3 children: "+ConterFor3+"\n"+
                        "Number of families with 4 or more children: "+ConterFor4+"\n"+                           
                        "The most common number of children is "+max+EndOfsentence);
		}
	}
    }